# frozen_string_literal: true

source "https://rubygems.org"

gem "cucumber", "5.2"
gem "capybara", "3.36"
gem "site_prism"
gem "selenium-webdriver", " 3.142.7"
gem "rspec", "3.10"
gem "rufo", "0.13.0"
gem "pry"
gem "allure-cucumber", "2.13.6.4"
